### ISSUE TITLE
Support for IPv6 is missing

### ISSUE THREAD

**Issue by MEschenbacher** [kilo-io/iptables_parser#10]
When parsing IPv6 addresses/networks, the parser thinks it's a DNS name

    Error: failed to parse line, skipping rest ":db8::/64 -j ACCEPT" of the line: "2001" is not a valid DNS name

**Comment by leonnicolas** [comment]
I see that https://github.com/kilo-io/iptables_parser/blob/275b7c93e8a7588940a64c72b9ba462d254ba1bc/parser.go#L209 does not support IPv6 without a network mask because it would add `/32` in case there is not network mask. However, in your case I would have expected that https://pkg.go.dev/net#ParseCIDR would still return no error. It does support IPv6 addresses after all.

> the parser thinks it's a DNS name

If https://pkg.go.dev/net#ParseCIDR fails, it will just think it is DNS name. So the thing to find out is, why did net.ParseCIDR return a non nil error.

Do you mind adding a test with an IPv6 address?

**Comment by MEschenbacher** [comment]
I've added a test and the fix for it.

I'm probably going to have to address the thing with the big `TODO` regarding `/32` as well, soon.
